from __future__ import annotations

from pathlib import Path

from bundlebleed.verification.models import RequestDraft, VerificationDraft


def _render_http(draft: RequestDraft) -> str:
    lines = [f"{draft.method} {draft.url} HTTP/1.1"]
    for key, value in draft.headers.items():
        lines.append(f"{key}: {value}")
    if draft.comment:
        lines += ["", f"# {draft.comment}"]
    return "\n".join(lines) + "\n"


def _render_curl(draft: RequestDraft) -> str:
    parts = ["curl", "-i", "-X", draft.method]
    for key, value in draft.headers.items():
        parts.append(f'-H "{key}: {value}"')
    parts.append(f'"{draft.url}"')
    return " ".join(parts)


def write_verification_artifacts(draft: VerificationDraft, output_dir: Path) -> list[Path]:
    """Write request-baseline.http / request-test.http / curl-reproduce.sh
    into <output_dir>/evidence/<hypothesis_id>/. Never writes a real
    credential value — headers here only ever hold the placeholder that
    `draft_verification` set.
    """
    bundle_dir = output_dir / "evidence" / draft.hypothesis_id
    bundle_dir.mkdir(parents=True, exist_ok=True)

    baseline_path = bundle_dir / "request-baseline.http"
    test_path = bundle_dir / "request-test.http"
    curl_path = bundle_dir / "curl-reproduce.sh"

    baseline_path.write_text(_render_http(draft.baseline))
    test_path.write_text(_render_http(draft.test))

    script_lines = [
        "#!/bin/sh",
        "# Generated by BundleBleed. Nothing here has been run automatically.",
        *[f"# {note}" for note in draft.notes],
        "",
        "echo '--- baseline ---'",
        _render_curl(draft.baseline),
        "",
        "echo '--- test ---'",
        _render_curl(draft.test),
        "",
    ]
    curl_path.write_text("\n".join(script_lines) + "\n")

    return [baseline_path, test_path, curl_path]
